In [2]:
import pymatgen as mp
import numpy as np
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen import MPRester

with MPRester("6gQTbf2KhBi8mC40") as m:

    # Structure for material id
    structure = m.get_structure_by_material_id("mp-9166")

In [12]:
new_s = SpacegroupAnalyzer(structure).get_primitive_standard_structure()
atomes = structure.sites
coord_C = atomes[0].coords
coord_N1 = atomes[1].coords
coord_N2 = atomes[2].coords
coord_Mg = atomes[3].coords

print(coord_C)
print(coord_N1)
print(coord_N2)
print(coord_Mg)

[2.24718819 1.39798734 6.59488342]
[1.85731583 1.15544574 5.45071455]
[2.63706056 1.64052895 7.7390523 ]
[0. 0. 0.]


In [19]:
sga = SpacegroupAnalyzer(new_s)
sym = sga.get_symmetry_operations()

rotation = sga.get_symmetry_operations()[9].rotation_matrix
tau_1 = sga.get_symmetry_operations()[9].translation_vector
print("Equation: \n")
print(rotation, "*", coord_C, "+", tau_1, "=", sga.get_symmetry_operations()[9].operate(coord_C))

Equation: 

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] * [2.24718819 1.39798734 6.59488342] + [0. 0. 0.] = [2.24718819 6.59488342 1.39798734]


<img src="rotation1.jpg" style="width:600px;height:600px"/>

<img src="rotation11.jpg" style="width:600px;height:600px"/>

In [22]:
inversion = sga.get_symmetry_operations()[1].rotation_matrix
tau_2 = sga.get_symmetry_operations()[1].translation_vector
print("Equation: \n")
print(inversion, "*", coord_N1, "+", tau_2, "=", sga.get_symmetry_operations()[1].operate(coord_N1))

Equation: 

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]] * [1.85731583 1.15544574 5.45071455] + [0. 0. 0.] = [-1.85731583 -1.15544574 -5.45071455]


<img src="inv_1.jpg" style="width:600px;height:600px"/>

<img src="inv_2.jpg" style="width:600px;height:600px"/>

In [24]:
rotation = sga.get_symmetry_operations()[9].rotation_matrix
tau_1 = sga.get_symmetry_operations()[9].translation_vector
roto = sga.get_symmetry_operations()[9].operate(coord_N2)
print("Equation liée à la rotation: \n")
print(rotation, "*", coord_N2, "+", tau_1, "=", roto)
print("\n")

inversion = sga.get_symmetry_operations()[1].rotation_matrix
tau_2 = sga.get_symmetry_operations()[1].translation_vector
print("Equation liée à l'inversion de N2 ayant déjà subi une rotation: \n")
print(inversion, "*", roto, "+", tau_2, "=", sga.get_symmetry_operations()[1].operate(roto))

Equation liée à la rotation: 

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] * [2.63706056 1.64052895 7.7390523 ] + [0. 0. 0.] = [2.63706056 7.7390523  1.64052895]


Equation liée à l'inversion de N2 ayant déjà subi une rotation: 

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]] * [2.63706056 7.7390523  1.64052895] + [0. 0. 0.] = [-2.63706056 -7.7390523  -1.64052895]


<img src="roto1.jpg" style="width:600px;height:600px"/>

<img src="roto2.jpg" style="width:600px;height:600px"/>